---
# http://docs.ansible.com/ansible/galaxy.html
- src: carlba.gitconfig
  version: master
- src: carlba.bash_aliases
  version: master
- src: geerlingguy.pip
  version: master
- src: carlba.vim
  version: master
- src: carlba.tmux
  version: master
- src: carlba.dotfiles_minimal
  version: master
